name: CI Pipeline

on:
  push:
    branches:
      - master  # Trigger the pipeline on push to the master branch
  pull_request:
    branches:
      - master  # Trigger the pipeline on pull request to the master branch

jobs:
  build:
    runs-on: self-hosted  # Specify the VM to run the job on

    env:
      NODE_ENV: 'development'
      DOCKER_IMAGE: 'todo-app'
      DOCKER_TAG: ${{ github.run_number }}  # Use GitHub run number as the tag
      DOCKER_USERNAME: 'prasadsb'  # Your Docker Hub username

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js and install dependencies
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version, adjust if needed

    - name: Install dependencies
      run: |
        npm cache clean --force
        npm install

    # Step 3: Run tests
    - name: Run tests
      run: |
        sudo apt-get update
        sudo apt-get install -y psmisc  # Install psmisc to provide the fuser command
        fuser -k 3000/tcp || true  # Kill any process using port 3000
        npm test

    # Step 4: Build and run Docker container
    - name: Build and run Docker container
      run: |
        docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .
        docker tag ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
        
        # Stop and remove any existing container
        docker ps -q --filter "name=todo-app" | xargs -r docker stop
        docker ps -aq --filter "name=todo-app" | xargs -r docker rm
        
        # Run the new container
        docker run -d --name todo-app -p 3000:3000 ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

    # Step 5: Send email on failure
    - name: Send email on failure
      if: failure()  # Only run if the job fails
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}  # Gmail username
        password: ${{ secrets.EMAIL_PASSWORD }}  # Gmail App Password
        subject: "Pipeline Failed: ${{ github.repository }} - Build #${{ github.run_number }}"
        body: |
          The build for the repository `${{ github.repository }}` has failed.

          Build Number: ${{ github.run_number }}
          Check the logs at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        to: prasadbandagale2021.it@mmcoe.edu.in
        from: ${{ secrets.EMAIL_USERNAME }}  # Sender's email address
